# SPDX-FileCopyrightText: 2023 Joonas Rautiola <joinemm@pm.me>
# SPDX-License-Identifier: MPL-2.0
# https://git.joinemm.dev/miso-bot

services:
  nirn:
    container_name: miso-gateway
    image: "ghcr.io/germanoeich/nirn-proxy:main"
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - REQUEST_TIMEOUT=10000 # 10 seconds
    profiles: [prod, dev-extra]

  db:
    container_name: miso-db
    image: mariadb
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d:ro
      - ./sql/scheduled:/scripts:ro
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=bot
      - MARIADB_PASSWORD=botpw
      - MARIADB_DATABASE=misobot
      - MARIADB_ROOT_PASSWORD=secure-af
    profiles: [prod, dev, dev-extra]

  image-server:
    container_name: miso-image-server
    build: https://github.com/joinemm/html-imager.git#master
    restart: unless-stopped
    init: true
    expose:
      - 3000
    volumes:
      - ./html/static:/app/static:ro
      - ./html/templates:/app/templates:ro
    profiles: [prod, dev-extra]

  shlink:
    container_name: miso-shlink
    image: shlinkio/shlink:latest
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - DEFAULT_DOMAIN=url.misobot.xyz
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=maria
      - DB_NAME=shlink
      - DB_USER=bot
      - DB_PASSWORD=botpw
      - DB_HOST=db
    depends_on:
      - db
    profiles: [prod]

  bot-prod:
    container_name: miso-bot
    build: .
    command: python -O main.py
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=miso-db
      - IMAGE_SERVER_HOST=image-server
      - EMOJIFIER_HOST=emojifier
      - WEBSERVER_PORT=8080
      - WEBSERVER_HOSTNAME=0.0.0.0
      - USE_REDIS_CACHE=1
      - DISCORD_PROXY=http://nirn:8080
    tty: true
    profiles: [prod]

  bot-dev:
    container_name: miso-bot-dev
    build: .
    command: python -O main.py dev
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=miso-db
      - IMAGE_SERVER_HOST=image-server
      - WEBSERVER_PORT=8080
      - WEBSERVER_HOSTNAME=0.0.0.0
      - USE_REDIS_CACHE=1
    tty: true
    profiles: [dev, dev-extra]

  redis:
    container_name: miso-redis
    image: "redis:alpine"
    environment:
      - REDIS_REPLICATION_MODE=master
    expose:
      - 6379
    volumes:
      - redis-data:/data
    profiles: [prod, dev-extra]

networks:
  default:
    driver: bridge

volumes:
  database:
  shlink-database:
  redis-data:
